CREATE SCHEMA IF NOT EXISTS demo_users CHARACTER SET = 'utf16';
CREATE USER IF NOT EXISTS 'demo'@'%' IDENTIFIED BY 'logmein';
GRANT ALL PRIVILEGES ON demo_users.* TO 'demo'@'%' IDENTIFIED by 'logmein';
